# Pipeline for drone
workspace:
  base: /go
  
pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go run main.go
      
services:
  mongo:
    image: mongo:3.0
